### ISSUE TITLE
Listing Drafts or Listing tags ?

### ISSUE THREAD

**Issue by rmdes** [mapkyca/BashKnown#1]
I wanted to have a list of all the tags I ever used on my Known instance

OR 

a list of all the private posts I started. 

Would that be possible by fetching Known API & this plugin ?

**Comment by mapkyca** [comment]
Yes with an if, or no with a but.

The bash api calls the known api, so if it's possible to do via a known api endpoint (get or post) then it'll be possible to call via this tool.
