### ISSUE TITLE
Privacy of status post

### ISSUE THREAD

**Issue by ghost** [mapkyca/BashKnown#2]
Would it be possible to add an option to set the privacy of a post - Public , Members Only and Private ?
Thanks.

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/BashKnown/issues/2" class="u-in-reply-to"></a>You should be able to set anything that you can from the interface, since all this does is perform an authenticated POST.

**Comment by ghost** [comment]
OK , Thank you.
