### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by cdn** [mapkyca/BashKnown#3]
Now that Known itself is capable of multiple image attachments to an Image–type post, can this capability be added to the scripts?

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/BashKnown/issues/3" class="u-in-reply-to"></a>That would be cool!

Should just be a matter of adding square brackets to "photos", and then sending multiple -Fs for each filename (i.e. iterating through the remaining bash vars and treating them as files).

See https://medium.com/@petehouston/upload-files-with-curl-93064dcccc76

Not sure when I'll get to this though given everything I've got on atm, but PRs most welcome if you get impatient!

**Comment by cdn** [comment]
Is there any reason that one image (PNG) seemingly gets deleted in the course of being processed?

photo.sh slightly hacked for [], and appropriate MIME…

**Comment by cdn** [comment]
[] weren’t appreciated; helps if web server user/group own Uploads. #toomanywebroots

**Comment by cdn** [comment]
Pull request #5 should do it, provided no one puts spaces in their image names.
Does break compatibility with 0.9.9.

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/BashKnown/issues/3#issuecomment-380786271" class="u-in-reply-to"></a>Spaces *should* be handled by putting quotes around the name, or escaping with \, but ymmv!

Thanks for the PRs, and don't worry, I'm not overly fussed about backwards compatibility if it prevents moving forward. Besides, the official 0.9.9, is almost a year old at this point!

**Comment by cdn** [comment]
I have my main blog on 0.9.9 with an sqlite3 datastore, it tends to be twitchy when I try to upgrade the php side of Known.

Can I part–migrate code, like IdnoPlugins/Photo, and get the functionality?

**Comment by mapkyca** [comment]
<a href="https://github.com/mapkyca/BashKnown/issues/3#issuecomment-381068895" class="u-in-reply-to"></a>You mean upgrade the plugin without upgrading core..?

If so, that's yes with an if :)

Basically it depends on how old your core build is and whether the plugin depends on functionality that isn't present in your build. YMMV.

Sqlite back end is less travelled than mongo or mysql, so that probably goes to explain some of the twitchyness. Bug reports / PRs welcome to try and iron out some of those glitches!

**Comment by cdn** [comment]
More to port over: "Call to undefined method Idno\Core\Language::_()"

**Comment by cdn** [comment]
At a minimum, Idno/Core/Language.php and Idno/Core/Input.php to accompany the files of the Photo plug–in.
